### ISSUE TITLE
Checks for impartial block comment

### ISSUE THREAD

**Issue by king2b3** [stegnerw/compiler_theory_test_programs#11]
/*/ */

Should just open and close once, not open once and close twice

**Comment by stegnerw** [comment]
@king2b3 You have a modified test program that includes this, right? If you want, you can just go ahead and toss that in a branch and pull request it.

**Comment by king2b3** [comment]
I don't have one specifically, I just threw it in one of them. I can do that though.

**Comment by stegnerw** [comment]
I'm going to just toss this in test1.src since it already has nested block comments
