### ISSUE TITLE
Single line comment in multiline comment - Correct

### ISSUE THREAD

**Issue by king2b3** [stegnerw/compiler_theory_test_programs#15]
EX
- /* This is a test // test */

**Comment by stegnerw** [comment]
Added a case for this in my branch ddb07d2200d98a958d4d2d126b9ad161e6dbea93 so this will close when we merge in my branch.

**Comment by stegnerw** [comment]
There's also an example of this in `incorrect/test2.src`. I'm leaving the new test in my branch so we have one in `correct/`, but I consider this closed.
