### ISSUE TITLE
Scoping errors - Outside of scope - Incorrect

### ISSUE THREAD

**Issue by king2b3** [stegnerw/compiler_theory_test_programs#18]
A few examples of this

1. Undefined variable
2. Local variable is used in an outside space

**Comment by stegnerw** [comment]
`incorrect/test1b.src` has 2 spots which fail because they are forward references to a variable `i`, which is globally defined after the references. I'll go ahead and add a couple more examples just for thorough coverage.

**Comment by stegnerw** [comment]
Update: Added this example in a commit on my branch: 83a15c3163008d97effd20d6401226ee853c76e4
